apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "basic.fullname" . }}
  namespace: default
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "basic.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "basic.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.application.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- if .Values.volumes.enabled }}
          volumeMounts:
            - mountPath: /var/www/html
              name: {{ .Values.application.name }}-volume
          {{- end}}
          env:
          {{- if eq .Values.application.type "wordpress" }}
          - name: WORDPRESS_DB_HOST
            valueFrom:
              secretKeyRef:
                name: {{ .Values.application.name }}-db
                key: host
          - name: WORDPRESS_DB_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.application.name }}-db
                key: login
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.application.name }}-db
                key: password
          - name: WORDPRESS_DB_NAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.application.name }}-db
                key: dbname
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
    {{- if .Values.volumes.enabled }}
      volumes:
        - name: {{ .Values.application.name }}-volume
          {{- if hasKey .Values.volumes.type "nfs" }}
          {{- with .Values.volumes.type.nfs }}
          nfs:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }} 
    {{- end }}
