apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "basic.fullname" . }}
  labels:
    {{- include "basic.labels" . | nindent 4 }}
  namespace: default
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "basic.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "basic.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "50Mi"
              cpu: "10m"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
