---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: {{ .Values.appName }}
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: {{ .Values.appName }}
  policy:
    semver:
      range: '>=0.0.1'

