{{- if .Values.ingress.enabled -}}
{{- $fullName := include "basic.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.appName }}
  namespace: default
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $release.Values.appName }}
                port:
                  number: {{ $svcPort }}
    {{- end }}
{{- end }}
