{{- if .Values.ingress.enabled -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: default
  {{- if hasKey .Values.ingress "tls" }}
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt
    cert-manager.io/issue-temporary-certificate: "true"
    acme.cert-manager.io/http01-edit-in-place: "true"
  {{- end }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}
                port:
                  number: {{ $svcPort }}
    {{- end }}
  {{- if hasKey .Values.ingress "tls" }}
  tls:
  {{- range .Values.ingress.tls }}
    - secretName: {{ $.Release.Name }}-tls
      hosts:
        - {{ .hosts | first  }}
  {{- end }}
  {{- end }}
  {{- end -}}
