{{- if .Values.ingress.enabled -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: default
  {{- if .Values.ingress.tls -}}
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
  {{- end -}}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}
                port:
                  number: {{ $svcPort }}
  {{- if .Values.ingress.tls -}}
  tls:
    - secretName: {{ $.Release.Name }}-tls
      hosts:
        - {{ .host | quote }}
  {{- end -}}
    {{- end }}
{{- end }}
