{{- if and .Values.volumes.enabled .Values.database.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-init-websitedir"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      containers:
        - name: alpine
          image: arm32v7/alpine:3.17.2
          env:
          - name: WEBSITE_DIR
            value: "/storage/{{ .Release.Name }}"
          volumeMounts:
            - mountPath: /storage
              name: {{ .Release.Name }}-volume
          command: ["/bin/mkdir"]
          args: ["$(WEBSITE_DIR)"]
      volumes:
        - name: {{ .Release.Name }}-volume
          {{- if hasKey .Values.volumes.type "nfs" }}
          {{- with .Values.volumes.type.nfs }}
          nfs:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}   
{{- end }}