apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: default
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "basic.selectorLabels" . | nindent 4 }}
