apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: default
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "basic.selectorLabels" . | nindent 4 }}
